[workspace]
resolver = "3"
members = [
    "crates/transferred-core",
    "crates/transferred-postgres",
    "crates/transferred-files",
    "crates/transferred-py",
]

[workspace.package]
version = "0.0.3"
edition = "2024"
license = "MIT"
repository = "https://github.com/skatromb/transferred"

[workspace.dependencies]
transferred-core = { path = "crates/transferred-core", version = "0.0.3" }
transferred-files = { path = "crates/transferred-files", version = "0.0.3" }
transferred-postgres = { path = "crates/transferred-postgres", version = "0.0.3" }
arrow = { version = "59", features = ["prettyprint"] }
arrow-schema = "59"
tokio = { version = "1.53", features = ["rt-multi-thread", "macros", "sync", "io-util", "net", "time", "fs"] }
tokio-stream = "0.1"
futures = "0.3"
async-trait = "0.1"
tracing = "0.1"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
indexing_slicing = "deny"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"
