# Readable code and best practices from `restriction`
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
allow-unwrap-in-tests = true
allowed-idents-below-min-chars = ["i", "n", "Io", "py", "to"]
min-ident-chars-threshold = 2

# Thresholds from wemake-python-styleguide
cognitive-complexity-threshold = 12
disallowed-names = [
    "arr", "bar", "baz", "content", "contents", "data", "do", "false", "foo", "ham",
    "handle", "handler", "info", "item", "items", "no", "obj", "objects", "objs", "param",
    "params", "parameters", "result", "results", "some", "spam", "temp", "tmp", "true", "val",
    "vals", "value", "values", "var", "variable", "vars",
]
excessive-nesting-threshold = 4
max-fn-params-bools = 1
max-struct-bools = 1
too-many-arguments-threshold = 5
too-many-lines-threshold = 25
type-complexity-threshold = 75
