# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "ParquetDestination",
    "ParquetSource",
    "RunReport",
    "Transfer",
]

@typing.final
class ParquetDestination:
    r"""
    Local single-file Parquet destination. Writes via tmp file + atomic rename.
    """
    def __new__(cls, path: builtins.str | os.PathLike | pathlib.Path, compression: builtins.str = 'zstd') -> ParquetDestination: ...

@typing.final
class ParquetSource:
    r"""
    Local single-file Parquet source. No I/O performed at construction.
    """
    def __new__(cls, path: builtins.str | os.PathLike | pathlib.Path) -> ParquetSource: ...

@typing.final
class RunReport:
    r"""
    Post-run statistics returned by `Transfer.run()`.
    """
    @property
    def rows(self) -> builtins.int:
        r"""
        Total rows written.
        """
    @property
    def bytes_written(self) -> builtins.int:
        r"""
        Total bytes written to the destination.
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Wall-clock duration of the transfer, in seconds.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Transfer:
    r"""
    Orchestrates a single source → destination run. Single-shot: each instance can run once.
    """
    def __new__(cls, source: typing.Any, destination: typing.Any) -> Transfer: ...
    def run(self) -> RunReport: ...

