# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "RunReport",
]

@typing.final
class RunReport:
    r"""
    Post-run statistics returned by `Transfer.run()`.
    
    Attributes:
        `rows`: Total rows written.
        `bytes_written`: Total bytes written to the destination.
        `written_objects`: Identifiers of what was written (paths, URIs, tables).
        `duration_seconds`: Wall-clock duration of the transfer, in seconds.
    
    Example:
        ```py
        >>> report = Transfer(source=..., destination=...).run()
        >>> print(report)
        RunReport:
          rows: 12,481,902
          written: 1.40 GiB
          duration: 4s 218ms
          written objects:
            out/part-00001.parquet
            out/part-00002.parquet
        ```
    """
    @property
    def rows(self) -> builtins.int:
        r"""
        Total rows written.
        """
    @property
    def bytes_written(self) -> builtins.int:
        r"""
        Total bytes written to the destination.
        """
    @property
    def written_objects(self) -> builtins.list[builtins.str]:
        r"""
        Identifiers of what the destination wrote (file paths, URIs, tables).
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Wall-clock duration of the transfer, in seconds.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class _ArrowSource:
    r"""
    Internal `PyO3` wrapper around a pyarrow `RecordBatchReader`. Constructed by
    the user-facing Python `ArrowSource`; not intended to be used directly.
    """
    def __new__(cls, reader: typing.Any) -> typing.Self: ...

@typing.final
class _FilesDestination:
    r"""
    Internal `PyO3` wrapper around `transferred_files::FilesDestination`.
    """
    def __new__(cls, path: builtins.str | os.PathLike | pathlib.Path, format: typing.Any, single_file: builtins.bool = False) -> typing.Self: ...

@typing.final
class _FilesSource:
    r"""
    Internal `PyO3` wrapper around `transferred_files::FilesSource`.
    """
    def __new__(cls, path: str | os.PathLike | list[str | os.PathLike], format: typing.Any) -> typing.Self: ...

@typing.final
class _Parquet:
    r"""
    Internal `PyO3` wrapper around `transferred_files::Parquet`.
    """
    def __new__(cls, compression: typing.Optional[builtins.str]) -> _Parquet: ...

class _Transfer:
    r"""
    Internal `PyO3` wrapper around `transferred_core::Transfer`. Subclassed by the
    user-facing Python `Transfer`; not used directly.
    """
    def __new__(cls, source: typing.Any, destination: typing.Any) -> typing.Self: ...
    def run(self) -> RunReport: ...


class TransferredError(Exception):
    """Base exception for all `transferred` failures.

    Subclasses: `SourceError` (and `EmptySourceError`), `DestinationError`, `ArrowError`, `IoError`.

    Example:
        ```py
        >>> from transferred import Transfer, TransferredError
        >>> try:
        ...     Transfer(source=..., destination=...).run()
        ... except TransferredError as e:
        ...     print(f"transfer failed: {e}")
        ```
    """

class SourceError(TransferredError):
    """Source read failed (file missing, malformed Parquet, etc.)."""

class EmptySourceError(SourceError):
    """Source produced no batches — nothing to transfer."""

class DestinationError(TransferredError):
    """Destination write failed (permission denied, disk full, schema mismatch)."""

class ArrowError(TransferredError):
    """Arrow schema or array conversion failed."""

class IoError(TransferredError):
    """Filesystem I/O error not attributable to source or destination logic."""
