name: Dependabot auto-merge

# Workaround to not spam this check in PR's check list
on:
  workflow_run:
    workflows: [Check]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Enable auto-merge
    if: >-
      github.event.workflow_run.actor.login == 'dependabot[bot]'
      && github.event.workflow_run.event == 'pull_request'
      && github.event.workflow_run.conclusion == 'success'
      && contains(github.event.workflow_run.head_commit.message, 'update-type: version-update:semver-')
      && !contains(github.event.workflow_run.head_commit.message, 'update-type: version-update:semver-major')
    runs-on: ubuntu-24.04-arm
    steps:
      - run: gh pr merge --auto --squash "$BRANCH"
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch }}
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
